# Generated by Django 2.1.4 on 2018-12-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep13', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
